### ISSUE TITLE
RuntimeException: E_MISSING_CONFIG

### ISSUE THREAD

**Issue by danielsalles** [nrempel/adonis-kue#15]
I'm a bit confused to set up adonis-kue.
I followed step by step the readme documentation, and even then I have had problems getting it to work. When I go to dispatch a job, it returns the following error.
```
2018-02-22T20:19:31.792Z - warning: 
  WARNING: Adonis has detected an unhandled promise rejection, which may
  cause undesired behavior in production.
  To stop this warning, use catch() on promises and wrap await
  calls inside try/catch.

RuntimeException: E_MISSING_CONFIG: redis://localhost:6379 is not defined inside config/redis.js file
> More details: https://err.sh/adonisjs/errors/E_MISSING_CONFIG
    at Function.missingConfig (/home/daniel/dev/vacinadigital/api/monolith/node_modules/@adonisjs/redis/node_modules/@adonisjs/generic-exceptions/src/RuntimeException.js:38:12)
    at Proxy.connection (/home/daniel/dev/vacinadigital/api/monolith/node_modules/@adonisjs/redis/src/Redis/index.js:92:33)
    at createClientFactory (/home/daniel/dev/vacinadigital/api/monolith/node_modules/adonis-kue/src/Kue/index.js:30:39)
    at Object.exports.createClient (/home/daniel/dev/vacinadigital/api/monolith/node_modules/kue/lib/redis.js:62:31)
    at new Queue (/home/daniel/dev/vacinadigital/api/monolith/node_modules/kue/lib/kue.js:99:52)
    at Function.exports.createQueue (/home/daniel/dev/vacinadigital/api/monolith/node_modules/kue/lib/kue.js:70:23)
    at Kue.get instance [as instance] (/home/daniel/dev/vacinadigital/api/monolith/node_modules/adonis-kue/src/Kue/index.js:44:28)
    at Kue.dispatch (/home/daniel/dev/vacinadigital/api/monolith/node_modules/adonis-kue/src/Kue/index.js:63:22)
    at Object.TokenHook.addTokenQueue (/home/daniel/dev/vacinadigital/api/monolith/app/Models/Hooks/TokenHook.js:18:19)
    at Hooks.exec (/home/daniel/dev/vacinadigital/api/monolith/node_modules/@adonisjs/lucid/src/Lucid/Hooks/index.js:166:13)
    at Proxy._insert (/home/daniel/dev/vacinadigital/api/monolith/node_modules/@adonisjs/lucid/src/Lucid/Model/index.js:695:41)
    at <anonymous>
```

Now I will show my settings:
```
# kue
KUE_CONNECTION=redis://localhost:6379

# redis
REDIS_CONNECTION=local
```

config/redis.js
```js
'use strict'

/*
|--------------------------------------------------------------------------
| Redis Configuaration
|--------------------------------------------------------------------------
|
| Here we define the configuration for redis server. A single application
| can make use of multiple redis connections using the redis provider.
|
*/

const Env = use('Env')

module.exports = {
  /*
  |--------------------------------------------------------------------------
  | connection
  |--------------------------------------------------------------------------
  |
  | Redis connection to be used by default.
  |
  */
  connection: Env.get('REDIS_CONNECTION', 'local'),

  /*
  |--------------------------------------------------------------------------
  | local connection config
  |--------------------------------------------------------------------------
  |
  | Configuration for a named connection.
  |
  */
  local: {
    host: '127.0.0.1',
    port: 6379,
    password: null,
    db: 0,
    keyPrefix: ''
  },

  /*
  |--------------------------------------------------------------------------
  | cluster config
  |--------------------------------------------------------------------------
  |
  | Below is the configuration for the redis cluster.
  |
  */
  cluster: {
    clusters: [{
      host: '127.0.0.1',
      port: 6379,
      password: null,
      db: 0
    },
    {
      host: '127.0.0.1',
      port: 6380,
      password: null,
      db: 0
    }]
  }
}
```

config/kue.js
```js
'use strict'

const Env = use('Env')

module.exports = {
  // redis connection
  connection: Env.get('KUE_CONNECTION', 'kue')
}

```

Something that passed in my eyes?

**Comment by danielsalles** [comment]
I solved the problem. But I will leave the issue open because there is a lack of information in the readme.

**Comment by nrempel** [comment]
Hey @danielsalles, glad you got it working.

Do you mind making a pull request to update the README file?

**Comment by jericopulvera** [comment]
@danielsalles how did you solve this?
